### ISSUE TITLE
AQ20: Instance

### ISSUE THREAD

**Issue by m-laniakea** [elysium-project/server#151]
- [ ] #145 Kurinnaxx
- [ ] #146 General Rajaxx
- [ ] #147 Moam 
- [ ] #148 Buru the Gorger
- [ ] #149 Ayamiss the Hunter
- [ ] #150 Ossirian the Unscarred
- [ ] Loot tables
- [ ] Overall
