### ISSUE TITLE
Shifting Sands: Charge of the Dragonflights Prerequisites

### ISSUE THREAD

**Issue by m-laniakea** [elysium-project/server#155]
- [x] #152 Only One May Rise
- [x] #153 The Path of the Righteous
- [x] #154 A Pawn on the Eternal Board
