### ISSUE TITLE
Shifting Sands: Green Scepter Shard

### ISSUE THREAD

**Issue by m-laniakea** [elysium-project/server#160]
- [x] #156 Scepter Green: Eranikus, Tyrant of the Dream
- [x]           Tyrande and Remulos 
- [x] #157  The Nightmare's Corruption
- [ ] #158  Twilight Corrupter
- [ ] #159  The Nightmare Manifests
- [x] The Champion Returns
