### ISSUE TITLE
Shifting Sands: Blue Scepter Shard

### ISSUE THREAD

**Issue by m-laniakea** [elysium-project/server#169]
- [x] #162 Magical Ledger
- [x] #163 Narain's Scrying Goggles
- [x] #164 500 Pound Chicken
- [x] #165 Decoy!
- [x] #166 Draconic for Dummies: Volume II
- [x] #167 The Wrath of Neptulon
- [x] #168 Maws Encounter
