### ISSUE TITLE
Scepter of the Shifting Sands

### ISSUE THREAD

**Issue by m-laniakea** [elysium-project/server#172]
- [x] #155 Charge of the Dragonflights Prerequisites
- [x] #161 Red Scepter Shard
- [ ] #160 Green Scepter Shard
- [x] #169 Blue Scepter Shard
- [x] The Might of Kalimdor
- [x] #170 Bang a Gong!
- [x] #171 10 Hour War Event
- [x] Treasure of the Timeless One
