### ISSUE TITLE
Patch 1.9 Release

### ISSUE THREAD

**Issue by m-laniakea** [elysium-project/server#173]
- [x] #172 Scepter of the Shifting Sands
- [ ] #151 Ruins of Ahn'Qiraj
- [x] #144 Temple of Ahn'Qiraj
- [x] Quest content
