### ISSUE TITLE
Dev Update 2017.04.04

### ISSUE THREAD

**Issue by m-laniakea** [elysium-project/server#175]
**Content Updates**
- [x] #93  Fixes for RFD escort ritual
- [x] #96  Script/Silithus: Improve Eternal Board scene

**Mechanics**
- [x] #24   Quest Compendium of the Fallen should be unavailable to Undead
- [x] #56  Trade window glitch: The scam prevention system prevented players from accepting
- [x] #60  Party leader switching when zoning into instance fixes
- [x] #71  Druid Aquatic Form Missing
~~#89  Fix for transports on MacOS~~
- [x] #101 Fix for healthstone stacking
- [x] #103 Sweeping strike fix

**Environment Mechanics**
- [x] #19  Bug 3688. Change damage school from frost to nature on Noxxion and his adds
~~#43 Implement Event Based Timers. **Changes Lucifron Script**~~
- [x] #36  fix for issue 33 - thrash abuse fix 
- [x] #37  fix for issue 34 - ah-humanoid spells
- [x] #55  Fix for issue 3456: Shadow Vulnerability proc exceptions
- [x] #100 Fix for flee prevention aura not removing flee effects 
- [x] #114 Improvements to the despawn mechanics

**Text Changes**
- [x] #18  Fix: Level up hp/mana text
- [x] #45  Bugtracker #1887 & Level up stat fixes
- [x] #49  Small changes to Majordomo's texts

**Commands**
- [x] #20  .gocorpse command
- [x] #22   .go xyzo command
- [x] #46  .quest command changes
~~#50  Command: Add .groupinfo command~~
- [x] #51  .lookup player name command
- [x] #39  Make the .ban command remove characters from the world (instantly)

**Comment by shmgiy429** [comment]
Awesome, some really frustrating bugs are fixed in there; thanks to all the contributors for their time and effort!

**Comment by m-laniakea** [comment]
@Fr4nsson, an update from QA: #37 Is working, except for [Stormgarde Troll Hunter](http://db.vanillagaming.org/?npc=2583#abilities): Doesn't use Shadow Word: Pain.

**Comment by m-laniakea** [comment]
@henkethebenke, from QA: Majordomo still does not have any text, and doesn't play [A_ExecutusArrival04](http://www.wowhead.com/npc=12018/majordomo-executus#sounds) (was like this before your changes), if you want to take a look at it.

**Comment by QAkvastskaft** [comment]
#114 Confirmed fixed on PTR. Mobs now de-spawn after a set time regardless of being "reset" by being put in combat again. Tested on http://www.wowhead.com/quest=992/gadgetzan-water-survey which spawn 2 mobs that de-spawn after 10 minutes  

#103 Confirmed fixed on PTR. Sweeping strike damage is now exactly the same as damage on primary mob. Execute provides an auto-attack strike on the "sweeped" target

**Comment by QAkvastskaft** [comment]
#20 is confirmed working on PTR

#50 is NOT added to PTR and cannot be tested

**Comment by QAkvastskaft** [comment]
#96 looks good. my only comments is that Fandral saying damned is misspelled.
He says "damed"
This is the correct text "I want nothing to do with Silithus, the Qiraji and least of all, any damned dragons!"
