### ISSUE TITLE
Dev Update 2017.04.19

### ISSUE THREAD

**Issue by m-laniakea** [elysium-project/server#273]
**Content Updates**
- [x] #202 Make quest "Letter to Stormpike" require "Encrypted Letter" to be completed first.
- [x] #133 Changed the npcflag to include gossip for Archmage Xylem + Gossip (**Make sure he's only offering quests he's supposed to**)
- [x] #215 Implemented Stratholme postboxes
- [x] #179 Implemented the Warchief's Blessing event
- [ ] #224 Scripts/Blackwing Lair: Implement Scepter Red Shard Event
- [x] #220 Update quest factions for Hive in the Tower (#1126)
- [x] #110 Fix for blasted lands quest completion
- [x] #272 Scepter Blue: Implement Azuregos' Ledger Quest 
- [x] #377 Naga Brazier should reset properly.
- [x] #374 Corpses should despawn when items are used on them. See PR for full details.
- [x] #356 Elemental Charms from Elemental Exiles in Arathi Highlands now work.
- [x] #363 Touch of Zanzil should now work. See PR for full details.
- [ ] #309 Arcanite Dragonling should now work.
- [x] #359 Mottled Screecher emote fix.
- [x] #364 Garr's adds can no longer resist Massive Eruption.
- [x] #352 Zone-based monster yells (such as from Azuregos) will now also play any associated audio.
- [x] #284 Some repeatable quests, such as Chen's Empty Keg, were not able to be accepted.
- [x] #280 Cat Carrier (White Kitten) is now a limited supply item (one per three hours).
- [x] #221 Various Uldaman fixes. Please see the PR.
- [x] #338 Lucifron should once again cast Impending Doom.
- [ ] #343 Fixed an issue with Warchief's Blessing event timers not resetting correctly.

**Mechanics**
- [x] #125 Fix to item set bonus removing auras
- [x] #225 Hide buff from Tier 2 set.
- [x] #188 fix bloodfang proc buff being parried or dodged
- [x] #208 Set blackout to only proc on shadow damage spells
- [x] #232 Fixes transportation issues on MacOS 
- [x] [#33](https://github.com/mygithome002/server/pull/33) Linken's Boomrang proc rate adjustments
- [x] #249 Fix for flurry not re-applying on last charge
- [x] #251 Add the passive attribute to argent dawn trinkets
- [x] [#39](https://github.com/mygithome002/server/pull/39) Shift-click loot fix for quest items
- [x] [#](https://github.com/elysium-project/server/commit/bf3df0926620b90655bfe40e1f767e759f264621) Hand of Justice: Remove 1s internal cooldown
- [x] [#](https://github.com/elysium-project/server/commit/a04decd5cccb50d7a3f2818ca85abe3d537f9a24) Spirit of Zandalar: Persists through death until 1.11
- [x] #276 Fixed issues with consumable cooldowns, allowing Whipper Root Tuber and health potions to be used together.
- [x] [#] Players should now be dismounted entering Booty Bay and when boarding a boat/zeppelin.
- [ ] #323 Persistent area auras (Blizzard/RoF/Volley/etc) are no longer affected by the debuff limit.
- [x] #351 Resists no longer remove Shadow Vulnerability charges.
- [x] #360 Fix to health potion regeneration mechanics. See PR for full details.
- [x] #350 Shield Spikes and Elemental Sharpening Stones are no longer removed by death.
- [x] #353 Hellfire will no longer ignore immunities.
- [x] #315 Ancient Mana Spring totem should now use the correct spell.
- [x] #326 Fixed an issue where feral druids were being given incorrect damage boosts from weapons with multiple damage types.
- [x] #290 Improved health/mana/energy regeneration timings. This should fix an issue where mages were not receiving enough regen ticks from Evocation (see bug report linked in PR) and should improve the accuracy of energy timers for rogues.

**Environment Mechanics**
- [x] #134 Fix to ghost water walking.
- [x] #124 Fixed Skeleton Immunities & Removed Hillsbrad Lion Stealth
- [x] #186 Vaelastrasz speech timer
- [x] #254 Fix skeletons without immunities
- [x] #230 Target Dummy fixes
- [x] [#36](https://github.com/mygithome002/server/pull/36) Polymorph: Reduced regen per tick 10%
- [x] #390 Stormwind City Patrols should now walk at the correct speed.
- [x] #380 Guard directions have been updated. See the pull request for full details.
- [x] #341 You can no longer pull pets with guns without also pulling their masters. See PR for full details.
- [x] #342 Environmental fire damage can now be absorbed or resisted.
- [x] #319 Various fixes to NPC pets. See PR for full details.
- [x] [#] Bosses can now detect invisible players (e.g. using an invisibility potion).
- [x] #355 The final Deadmines door should no longer get stuck in a closed state if a rogue attempts to pick it while a player fires the cannon using the blasting powder.
- [x] [#] Polymorphed creatures will only regenerate 10% of their health per tick rather than a third.
- [x] #299 Removing insignias from players should now behave correctly.
- [x] #287 Fixed an issue where if a player placed a quest item in a bank, further items of that type would not drop. See PR for full details.
- [x] [#] NPCs should no longer flee from active conversations.
- [x] #311 When a player uses a soulstone in a battleground, the insignia cursor should not be displayed when hovering your mouse over them.
- [x] #270 Changes to dispel mechanics, including Azuregos's magic reflect shield. See PR.
- [x] #302 Players killed by NPCs in Alterac Valley can now have their insignias removed.
- [x] #301 Fixed a visual error with NPC pet flags. Please see the screenshot in the PR.
- [x] #245 Fixes issues with shapeshifting items being used in conjunction with druid shapeshifting forms. See the PR for details.

**Objects**
- [ ] #222 DB/gameobject: Move Gromsblood Above Terrain (GUID #32304)

**Text Changes**
- [x] #131 Corrected the Quest text for the Woodland Protector
- [x] #176 Corrects the errors in quest relating to Fandral Staghelm 
- [x] #203 fix typo in quest beer basted boar ribs
- [x] #209 Change quest text to write <name> instead of "Mac"
- [x] #317 Some creatures incorrectly had gnoll aggro messages assigned to them. See PR.

**Commands**
- [x] #104 War Effort Debug commands
- [x] #233 Extend pinfo to display 2FA status, gold in mail inbox and gold in mail outbox
- [x] #294 Loot table debug command now accepts an optional parameter to specify the number of simulations to run.

**Misc**
- [ ] #79 Clients using non-English clients can now participate in the default channels (e.g. general and trade).
- [x] #279 Fixed an issue where the auction house was not returning all matching results. Please see the bug report in the PR for reproduction steps.
