### ISSUE TITLE
Dev Update 2017.05.00

### ISSUE THREAD

**Issue by m-laniakea** [elysium-project/server#731]
**Content Updates**
- [x] #421 Fix Pyrewood Ambush Quest
- [x] #442 Remove `Warden of the Alliance` quest from Watcher Callahan
- [x] #457 Ensure `A Hero's Reward` can be accepted
- [x] #460 Improve Wailing Caverns experience
- [x] #493 Corporal Splithoof can now be summoned during interaction with Fallen Hero
- [x] #498 Grimtotem Spying chests offer different secret notes
- [x] #674 Quest A Lost Master now requires a prerequisite
- [x] #697 Cave Mushrooms quest now has a start script
- [x] #686 Gubber Blump fixes
- [x] #xxx Fix Defusing the Threat reputation
- [x] #714 Added How Big a Threat II quest end script

**Mechanics**
- [x] #400 Make EffectHealMaxHealth affected by healing percent auras 
- [x] #433, #450 Improvements to Charge mechanics
- [x] #440 Fix Tauren scaling
- [x] #479 -> #823 Fix Darkmoon Card: Blue Dragon
- [x] #454 Possible Root DC fix
- [x] [#XXX](https://github.com/elysium-project/server/commit/c0e48ad6ad119f1ab22c9e550733928bc0203486) Add 2 minute cooldown to Poison Resistance Elixir
- [x] #507 Correct +Spell Damage versus type auras
- [x] #663 Prevent certain classes from parrying
- [x] #565 Shapeshifting fixes
- [x] #676 Prevent Warriors from retaining rage when switching stances
- [ ] #692 Fix Death States

**Spell Mechanics**
- [ ] #405 Prevent Shadow Vulnerability from stacking
- [x] #406 Seal of Righteousness fixes
- [x] #418 Fix being able to cast while CCed
- [ ] #458 Prevent casting while seated
- [x] #482 Add Bleed mechanic to Rip
- [x] #483 Knockback effects now have binary resists
- [ ] #439 Improvements to Charm release mechanics
- [x] #447, #523  Spell Coefficient overhaul
- [x] #506 Fix Magic Absorption talent
- [x] #512 Implement Improved Fire Ward
- [x] #570 Fix MC interrupt
- [x] #569 Correct Swiftmend and Regrowth interaction
- [ ] #541 Fix Ritual of Summoning
- [x] #626 Fix Earth's Grasp talent
- [x] #609 Eye for an Eye can now proc Vengeance
- [x] #597 Totems and Flash of Light can now proc spells
- [x] #647 Fix Ignite damage
- [x] #562 Fix Gouge CD reduction
- [x] #522 Fix Health Funnel spell
- [x] #532 Fix Blind
- [x] #645 Fix AOE proc behaviour
- [x] #682 Gnomish Cloaking device invisibility no longer removed at start of cast
- [x] #683 Fix Mind Soothe and Soothe Animal

**Environment Mechanics**

- [x] #421 Swimming Crabs no longer evade if attacked from afar
- [x] #423 Stratholme Cannon no longer instantly kills the wielder
- [x] #412 Update Skeleton Immunities
- [x] #304 Fix Myrmidon spawns in Herod encounter
- [x] #453 Prevent some pets from granting XP
- [ ] #452 Fix dungeon reset time after server restart
- [x] #481 Correct Dragonmaw Bonewarder abilities
- [x] #494 Arcanite Dragonling fixes
- [x] #495 Fix some lockboxes not being unlocked while trading
- [x] #205 Fix raid markers disappearing
- [ ] #544 Fix Core Rager threat
- [x] #511 Correct Rockwing Gargoyle spawning behaviour
- [x] #554 Dismount NPCs when in combat
- [x] #530 Fix Pet Channeling spells
- [ ] #588 Improve PvP flag mechanics
- [x] #612 Brumeran in Winterspring no longer stays in one place
- [x] #613 Added Portal Seeker
- [x] #550 Fix some NPCs not resetting to home
- [x] #671 NPCs no longer backstab from the front
- [x] #673 Cleaned up duplicate spawns
- [x] #669 Civilians now have PvP flags
- [x] #610 Adjust Onyxia's Deep Breath probability
- [ ] #680 Various AV fixes
- [x] #685 Misc DB fixes
~~- [x] #528 Vanquished Tentacle fix + Timbermaw Ancestor~~ "vanquished tentacle now does its intended damage but when it dies the body dosn't go away fully and after the cd the next charge is used to remove other than resummon it."
- [x] #346 Shimmering Flats NPC "Salt Flats Scavenger" uses Execute against >20% health targets

**Objects**
- [x] #434 Re-position Gromsblood near Dark Portal

**Text Changes**
- [x] #389 Corrected Bluffwatcher POI
- [x] #429 Stone of Binding respawn time reduced to 5 minutes
- [x] #414 Fix Jordan's Weapon Notes
- [x] #678 Improve GM Ticket note

**Misc**
- [ ] #734 Honor Marks should now be deleted from the mailbox within 24 hours
- [x] #555 Players can now see raid reset times
- [x] #722 Fix to chest loot events

**Comment by lequintal69** [comment]
Any chance to add  https://github.com/elysium-project/server/pull/528
been waiting so long for this fix

**Comment by m-laniakea** [comment]
@lequintal69 Done.

**Comment by brotalnia** [comment]
I just want to clarify that https://github.com/elysium-project/server/pull/714 supersedes https://github.com/elysium-project/server/pull/674 . We discussed it with kvastskaft and he agreed A Lost Master should probably require How Big a Threat 2 as is evidenced from the retail video.

**Comment by Ripper007** [comment]
Woohoo!

**Comment by yayalmao** [comment]
when will these changes be implemented?

**Comment by Phoosy** [comment]
When QA confirms the fixes in their QA realm, hence the "Fix Needs QA" tag.

**Comment by Slicy** [comment]
#XXX Add 2 minute cooldown to Poison Resistance Elixir 

This is not a "fix" or whatever though. It's a not needed change making an iconic item work way differently than it should in vanilla. The item never had 2 mins CD. That's a QA mistake more than anything.

**Comment by gonor** [comment]
A Hero`s Reward is still not available from Duke Hydraxis.
I am revered with Hydraxian Waterlords, and have completed the chain. The Chest is not clickable as well.
![a hero s reward not working](https://cloud.githubusercontent.com/assets/28951460/26449627/a1a71eb4-4196-11e7-89d5-7a8d0d75fedc.PNG)

Server: Zeth`Kur
refer to screenshot.
